# Generated by Django 2.2.3 on 2019-07-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_created_from_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='skill',
            field=models.CharField(max_length=255, null=True, verbose_name='Required Skill'),
        ),
    ]
