# Generated by Django 2.2.3 on 2019-07-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='education',
            field=models.CharField(max_length=255, null=True, verbose_name='Required Education'),
        ),
        migrations.AddField(
            model_name='lead',
            name='experience',
            field=models.CharField(max_length=255, null=True, verbose_name='Required Experience'),
        ),
        migrations.AddField(
            model_name='lead',
            name='required',
            field=models.CharField(max_length=255, null=True, verbose_name='Number of people required'),
        ),
    ]
