# Generated by Django 2.2.3 on 2019-07-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20190624_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisettings',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-created_on',)},
        ),
    ]
