# Generated by Django 2.2.3 on 2019-07-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_auto_20190618_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactlist',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='campaignlinkclick',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_link_click', to='marketing.Campaign'),
        ),
    ]
