# Generated by Django 2.2.3 on 2019-07-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_date_of_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
