# Generated by Django 2.2.3 on 2019-07-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190721_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
