# Generated by Django 2.2.3 on 2019-07-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='job_title',
        ),
    ]
