# Generated by Django 2.2.3 on 2019-07-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20190624_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'ordering': ('id',)},
        ),
    ]
