# Generated by Django 2.0.7 on 2019-07-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_auto_20190708_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='confirm_password',
        ),
    ]
